### ISSUE TITLE
how i can solve this problem requests.exceptions.SSLError

### ISSUE THREAD

**Issue by Dxter95** [Abregud/EthereumX-Sniping-Bot-Demo#4]
requests.exceptions.SSLError: HTTPSConnectionPool(host='main-light.eth.linkpool.io', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)')))

**Comment by Abregud** [comment]
This can usually be two things:

1. Firewall is blocking RPC node connection
2. The free node is used too much by all the free users on this github and you need to wait till you get a slot

That's why we sell the premium version with premium node as it's instant sniping. I apologize for the issues but free stuff is free stuff
